#!/nix/store/2r9n7fz1rxq088j6mi5s7izxdria6d5f-bash-5.1-p16/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "" "" "" "" "" "" "" "" "" ""

bspc config border_width         2
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Borders
bspc config normal_border_color   "#1a72f0"
bspc config focused_border_color  "#5285c5"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Launch Polybar

xrandr --output HDMI-0 --mode 1920x1080 --rate 120 &
bash $HOME/.config/polybar/launch.sh
